### PR TITLE
Added support for template: template.

### PR DESCRIPTION
**Pull request by ekulabuhov**
* Added support for template: template (initialization through variable).
* Added support for constructor initialization.

Hi! This extension is pretty awesome. Just fixing few bugs I found while working with my codebase.

I have zero experience working with TypeScript parser or developing VSCode extensions. So I might be overcomplicating some things. 

I still need to figure out how to add unit tests.

### CODE REVIEW

**Comment by ipatalas** [comment]
Hi there.

Great job 👍 
I was thinking about those features myself. Don't have such cases in my project though so I couldn't find much motivation. Thanks a lot for doing that.

Before I will merge that I have two small requests:
- please fix all tslint errors - they're breaking the build on Travis preventing the tests from being executed -> https://travis-ci.org/ipatalas/ngComponentUtility/jobs/339542493
- provide simple example code for the features introduced - that will make it easier to include it in the readme

Ad 1) I know tslint is not included in the project - my bad - will do that in the meantime to provide tooling for that. For now you'd have to install it globally (`npm install tslint -g`) if you don't have it yet.
Execute `tslint -p .` in project root folder then. Ignore the errors in **test/index.ts** (auto-generated and will be excluded globally)

Regarding your doubts about TS parser there is a great tool for that: https://astexplorer.net/
I've been using it extensively while developing this extension. It's really helping me understand the structure and how to traverse it.

I can merge it without unit tests but I encourage you to try writing them. It's not that difficult. Check **component.test.ts** for inspiration. All you have to do is basically prepare new test file with a component and that feature (one per feature please to keep them in isolation) and just write some asserts to verify if everything is all right. I can assist you in that if you'll need help.

**Comment by ekulabuhov** [comment]
Hi! Thanks for the detailed response! I hope to have some time to implement all your suggestions tomorrow.

I've actually used astexplorer to develop these changes :smile: It's so much more useful than the output you get in the debugger!

I'm also thinking about adding CodeLens support for reference count. What do you think? Have you done any research in that direction already?

**Comment by ipatalas** [comment]
That would be great! I've had an idea for almost any feature of Code API but I forgot where I've written it down :'(
Reference count would be great. Haven't done any research but Code API is really easy. Never had problems with it so I guess the hardest part will be to prepare the data.
I can assist you when you will have questions regarding the extension.

**Comment by ipatalas** [comment]
Well done. Can you please provide simple examples for those features so that it's clear what it does?
I understand the first one but not 100% sure about constructor initialization.

**Pull request merged**
